### ISSUE TITLE
Кнопки некрасивые (извините)

### ISSUE THREAD

**Issue by niyazm524** [niyazm524/AndroidSummer2020#11]
Имхо нечитаемо (низкая контрастность) и не оч красиво, можно сделать лучше 
![Screenshot_2020-07-10-23-13-00](https://user-images.githubusercontent.com/32315145/87197259-fc643d00-c302-11ea-8a97-ed81c26f1794.png)

А ещё лучше сделать в синих цветах, чтобы было соответствие со своей игрой (ну или просто сделать свой неповторимый стиль, но красивый)

**Comment by ddddi21** [comment]
можно просто в конце за раз поменять дизайн? или уже сейчас все начинать приводить в порядок?

**Comment by niyazm524** [comment]
> можно просто в конце за раз поменять дизайн? или уже сейчас все начинать приводить в порядок?

Лучше уже сейчас привести в порядок и потом держаться его (зачем создавать себе будущему лишнюю работу?)

**Comment by ddddi21** [comment]
справедливо. Тогда займусь всем дезигном
