### ISSUE TITLE
Прогресбар таймера лучше бы уменьшался, а не увеличивался

### ISSUE THREAD

**Issue by niyazm524** [niyazm524/AndroidSummer2020#13]
![Screenshot_2020-07-10-23-21-57](https://user-images.githubusercontent.com/32315145/87199928-3124c400-c304-11ea-8f57-2d5aee59b5c6.png)

Вообще не логичное поведение, время уменьшается, а прогресс увеличивается - зачем? (why?)

**Comment by ddddi21** [comment]
because it's made with Stackoverflow's help, а о другом я и не подумала

**Comment by niyazm524** [comment]
> because it's made with Stackoverflow's help, а о другом я и не подумала

Ахахахха ясно, ну удачи в десигнерских делах

**Comment by ddddi21** [comment]
ахахах, мерси
