### ISSUE TITLE
баг с прогресбаром(не опять а снова)

### ISSUE THREAD

**Issue by ddddi21** [niyazm524/AndroidSummer2020#42]
ну кароче я тут заметила что там если не вводить ответ, время истекает, переносит к табл а прогрессбар остается (а если вводить не остается) дада я беру(госпаде когда он уже пофиксится окончательно............)

**Comment by Destered** [comment]
Пофиксится тогда, когда ты пофиксишь (Конфуций 228 год до президентства Обамы)

**Comment by ddddi21** [comment]
я фиксю но выявляю баги тоже я. видимо надо второе перестать делатт......

**Comment by niyazm524** [comment]
он пификшен?

**Comment by ddddi21** [comment]
дэ
