### ISSUE TITLE
зочем абижаете ячейки

### ISSUE THREAD

**Issue by ddddi21** [niyazm524/AndroidSummer2020#48]
где в первой категории цена "200"?если в паке нет(а такова быть не должно ибо странно), то все равно нужно заполнить чем то пустоту в душе.....
![XcfZ-S3XOrs](https://user-images.githubusercontent.com/55531213/87421771-26a64b00-c5e0-11ea-9b86-c8a0e4c5eb48.jpg)

**Comment by Destered** [comment]
Посмотрим, проверим, ликвидируем

**Comment by Destered** [comment]
Данный вопрос есть( за 200), но он содержит аудиофайл, тем самым не подходит нам для приложения, приносим свои извинения. Не знаю, стоит ли что-то с этим делать

**Comment by ddddi21** [comment]
а че мы не можем что ли аудио вставить на поляну вопроса?

**Comment by niyazm524** [comment]
вы можете всё

**Comment by niyazm524** [comment]
зависит только от желания

**Comment by ddddi21** [comment]
Тимур, слышишь да?

**Comment by Destered** [comment]
Хочу наггетсы
