### ISSUE TITLE
вопросы не умещаются/прокручиваются

### ISSUE THREAD

**Issue by ddddi21** [niyazm524/AndroidSummer2020#49]
ну тут или размер или макс длина строки или скролл, я хз ну вы поняли
![-O8_QmlyC4Y](https://user-images.githubusercontent.com/55531213/87422587-910bbb00-c5e1-11ea-94e6-83d20ab33cbc.jpg)

**Comment by Destered** [comment]
Чекну

**Comment by ddddi21** [comment]
ай да tea moor check :3
