### ISSUE TITLE
ячейки едут своей дорогой, а должны быть в своих столбцах

### ISSUE THREAD

**Issue by ddddi21** [niyazm524/AndroidSummer2020#52]
у нас шо за свобода передвижения? (вторая строка в данном случае, но они все так себя ведут)
![gfgkziRPX50 (1)](https://user-images.githubusercontent.com/55531213/87471066-67c14e00-c626-11ea-9e8b-e2bfc29c05cd.jpg)
![fb8bBLBu-0o](https://user-images.githubusercontent.com/55531213/87471079-6bed6b80-c626-11ea-98b9-c6ae5ab66d1e.jpg)
![VVqo6CbgOoA](https://user-images.githubusercontent.com/55531213/87471085-6db72f00-c626-11ea-9910-3c2fc5a2f83e.jpg)
последовательное нажатие приводит к III съезду ячеек

**Comment by ddddi21** [comment]
так апдейт. это штука только в ветке Тимура так работает, в которой много что другое съехало, поэтому наверное (надеюсь) в мастере этого нет пока

**Comment by Destered** [comment]
И не будет, иссуе бесполезен
