### ISSUE TITLE
сделать презентацию к показу

### ISSUE THREAD

**Issue by ddddi21** [niyazm524/AndroidSummer2020#71]
можно старую переделать по сути

**Comment by GalievBulat** [comment]
старая норм

**Comment by Destered** [comment]
Надо прост убрать что не реализовали и добавить что сделали

**Comment by ddddi21** [comment]
В презентации на слайдах должна быть информация:
1) Концепция приложения
2) Команда (участник – роль – что реализовывал)

Наиль: ну да ну да пошел я
