### ISSUE TITLE
может по умолчанию еще паков добавим?

### ISSUE THREAD

**Issue by ddddi21** [niyazm524/AndroidSummer2020#73]
то есть там щас 3 пака устанавливаются вместе с приложением, мб хотя бы 5-7-10? разве это много по памяти выйдет? заодно и скролл. и просто так удобнее будет (все для пользователя), если больше паков сразу будут установлены

**Comment by GalievBulat** [comment]
там и так 30 МБ 3 пака весят а это уже много просто для встроенных вопросов

**Comment by ddddi21** [comment]
а да? я не думала что столько..
