### ISSUE TITLE
Картинки подсказок

### ISSUE THREAD

**Issue by Destered** [niyazm524/AndroidSummer2020#82]
Исправить отображение картинок
![image](https://user-images.githubusercontent.com/55531017/87814498-89137b80-c86c-11ea-8d52-9155e2282196.png)
![image](https://user-images.githubusercontent.com/55531017/87814548-9b8db500-c86c-11ea-8cd4-e23aa20b658a.png)

**Comment by ddddi21** [comment]
почему они у тебя съезжают? подправь там сам, я не знаю почему так. они прикреплены правильно

**Comment by GalievBulat** [comment]
![Снимок экрана (18)](https://user-images.githubusercontent.com/55531288/87845607-86973d00-c8d1-11ea-9775-ff03bee340fa.png)

**Comment by GalievBulat** [comment]
исправил
