### ISSUE TITLE
предлагаю задержку боту поставить на отвечать/ не отвечать

### ISSUE THREAD

**Issue by ddddi21** [niyazm524/AndroidSummer2020#99]
я щас поиграла, и неудобно когда ты еще не прочитал вопрос, а он уже отвечает. поставить задержку как при вводе ответа секунд на 3-5  +- и будет каеф

**Comment by Destered** [comment]
Так там стоит 3 секунды

**Comment by Destered** [comment]
Увеличил до 5(или 6)

**Comment by ddddi21** [comment]
давай хотя бы 7-8 что ли, там же иногда длинный текст. я таймер там тоже увеличу

**Comment by Destered** [comment]
Поднял до 8, если что поменяешь уже сама ><
